version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: Neo
      POSTGRES_PASSWORD: "0451"
      POSTGRES_DB: wb-service-db
    ports:
      - 5433:5432
    restart: on-failure

  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_USER: Neo
      POSTGRES_PASSWORD: "0451"
      POSTGRES_DB: wb-service-db-test
    ports:
      - 5434:5432
    restart: on-failure

  kafka:
    image: apache/kafka:4.0.1-rc0
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - postgres  

  kafka_test:
    image: apache/kafka:4.0.1-rc0
    container_name: kafka_test
    ports:
      - 9092:9092
    depends_on:
      - postgres_test