app:
  log_directory: ./logs
  logger_debug_mode: true
  workers: 5
  worker_restart_delay: 5s

server:
  port: "8081"
  read_timeout: 10s
  write_timeout: 10s
  max_header_bytes: 1048576

database:
  driver: postgres
  host: localhost
  port: 5433
  username: Neo
  dbname: wb-service-db
  sslmode: disable

cache:
  save_in_cache: true
  cache_size: 10
  background_cleanup: false
  cleanup_period: 30s
  order_ttl: 40s

kafka:
  consumer:
    brokers:
      - localhost:9092
    topic: orders
    client_id: order-consumer
    group_id: order-consumers
    enable_auto_commit: false
    auto_offset_reset: earliest
    session_timeout_ms: 10000
    max_poll_interval_ms: 300000
    save_order_retry_delay: 5s
    save_order_retry_max: 3
    commit_retry_delay: 5s
    commit_retry_max: 3
  producer:
    brokers:
      - localhost:9092
    topic: orders
    client_id: order-producer
    messages_to_send: 10
    acks: all
    retry_max: 3 
    linger_ms: 5
    batch_size: 65536
    compression_type: snappy
    enable_idempotence: true
  dlq:
    brokers:
      - localhost:9092
    topic: orders-dlq
    client_id: order-dlq-producer
    acks: all
    retry_max: 3
    linger_ms: 5
    batch_size: 65536
    compression_type: snappy
    enable_idempotence: true

notifier:
  telegram:
    chat_id: "805862991"
    