version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - 5433:5432
    restart: on-failure

  kafka:
    image: apache/kafka:4.0.1-rc0
    container_name: kafka
    ports:
      - 9092:9092
    depends_on:
      - postgres  


