basePath: /
definitions:
  github_com_Pur1st2EpicONE_WBTECH-sample-microservice_internal_models.Delivery:
    properties:
      address:
        type: string
      city:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
      region:
        type: string
      zip:
        type: string
    required:
    - address
    - city
    - email
    - name
    - phone
    - region
    - zip
    type: object
  github_com_Pur1st2EpicONE_WBTECH-sample-microservice_internal_models.Item:
    properties:
      brand:
        type: string
      chrt_id:
        type: integer
      name:
        type: string
      nm_id:
        type: integer
      price:
        type: number
      rid:
        type: string
      sale:
        type: integer
      size:
        type: string
      status:
        type: integer
      total_price:
        type: number
      track_number:
        type: string
    required:
    - brand
    - chrt_id
    - name
    - nm_id
    - price
    - rid
    - status
    - total_price
    - track_number
    type: object
  github_com_Pur1st2EpicONE_WBTECH-sample-microservice_internal_models.Order:
    properties:
      customer_id:
        type: string
      date_created:
        type: string
      delivery:
        $ref: '#/definitions/github_com_Pur1st2EpicONE_WBTECH-sample-microservice_internal_models.Delivery'
      delivery_service:
        type: string
      entry:
        type: string
      internal_signature:
        type: string
      items:
        items:
          $ref: '#/definitions/github_com_Pur1st2EpicONE_WBTECH-sample-microservice_internal_models.Item'
        type: array
      locale:
        type: string
      oof_shard:
        type: string
      order_uid:
        type: string
      payment:
        $ref: '#/definitions/github_com_Pur1st2EpicONE_WBTECH-sample-microservice_internal_models.Payment'
      shardkey:
        type: string
      sm_id:
        type: integer
      track_number:
        type: string
    required:
    - customer_id
    - date_created
    - delivery
    - delivery_service
    - entry
    - items
    - locale
    - oof_shard
    - order_uid
    - payment
    - shardkey
    - sm_id
    - track_number
    type: object
  github_com_Pur1st2EpicONE_WBTECH-sample-microservice_internal_models.Payment:
    properties:
      amount:
        type: number
      bank:
        type: string
      currency:
        type: string
      custom_fee:
        type: number
      delivery_cost:
        type: number
      goods_total:
        type: number
      payment_dt:
        type: integer
      provider:
        type: string
      request_id:
        type: string
      transaction:
        type: string
    required:
    - amount
    - currency
    - delivery_cost
    - goods_total
    - payment_dt
    - provider
    - transaction
    type: object
  internal_handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost:8081
info:
  contact: {}
  description: RESTful API for querying order information by order ID
  title: wb-service API
  version: "1.0"
paths:
  /api/v1/orders/{orderId}:
    get:
      description: 'Returns order details in JSON format.<br>Check <strong>X-Cache</strong>
        header for cache status: <strong>HIT</strong> (from cache) or <strong>MISS</strong>
        (from database)'
      parameters:
      - description: Order ID (UUID)
        in: path
        name: orderId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Order data
          headers:
            X-Cache:
              description: 'Cache status: HIT or MISS'
              type: string
          schema:
            $ref: '#/definitions/github_com_Pur1st2EpicONE_WBTECH-sample-microservice_internal_models.Order'
        "404":
          description: Order not found
          schema:
            $ref: '#/definitions/internal_handler.ErrorResponse'
        "500":
          description: Internal server error
          schema:
            $ref: '#/definitions/internal_handler.ErrorResponse'
      summary: Get order by UID with cache status indication
      tags:
      - Orders
swagger: "2.0"
