// Code generated by MockGen. DO NOT EDIT.
// Source: cache.go

// Package mock_cache is a generated GoMock package.
package mock_cache

import (
	context "context"
	reflect "reflect"

	models "github.com/Pur1st2EpicONE/WBTECH-sample-microservice/internal/models"
	logger "github.com/Pur1st2EpicONE/WBTECH-sample-microservice/pkg/logger"
	gomock "github.com/golang/mock/gomock"
)

// MockCache is a mock of Cache interface.
type MockCache struct {
	ctrl     *gomock.Controller
	recorder *MockCacheMockRecorder
}

// MockCacheMockRecorder is the mock recorder for MockCache.
type MockCacheMockRecorder struct {
	mock *MockCache
}

// NewMockCache creates a new mock instance.
func NewMockCache(ctrl *gomock.Controller) *MockCache {
	mock := &MockCache{ctrl: ctrl}
	mock.recorder = &MockCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCache) EXPECT() *MockCacheMockRecorder {
	return m.recorder
}

// CacheCleaner mocks base method.
func (m *MockCache) CacheCleaner(ctx context.Context, logger logger.Logger, dbStatus chan bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CacheCleaner", ctx, logger, dbStatus)
}

// CacheCleaner indicates an expected call of CacheCleaner.
func (mr *MockCacheMockRecorder) CacheCleaner(ctx, logger, dbStatus interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheCleaner", reflect.TypeOf((*MockCache)(nil).CacheCleaner), ctx, logger, dbStatus)
}

// CacheOrder mocks base method.
func (m *MockCache) CacheOrder(order *models.Order, logger logger.Logger) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CacheOrder", order, logger)
}

// CacheOrder indicates an expected call of CacheOrder.
func (mr *MockCacheMockRecorder) CacheOrder(order, logger interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CacheOrder", reflect.TypeOf((*MockCache)(nil).CacheOrder), order, logger)
}

// GetCachedOrder mocks base method.
func (m *MockCache) GetCachedOrder(orderID string) (*models.Order, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCachedOrder", orderID)
	ret0, _ := ret[0].(*models.Order)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCachedOrder indicates an expected call of GetCachedOrder.
func (mr *MockCacheMockRecorder) GetCachedOrder(orderID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCachedOrder", reflect.TypeOf((*MockCache)(nil).GetCachedOrder), orderID)
}
